課題③-2まで実装
nagamoridaiki/TaskList3 pull request #1
Opened 2020-12-30 03:26 UTC by nagamoridaiki

2020-12-30 12:51 UTC, myzktkyk requested changes
動作は問題ありませんでした。
コードのやや細かいところで指摘が何点かあります。

2020-12-30 12:51 UTC, myzktkyk commented on index.js
> +let inicialTableTag =
typo かな？と思います。
```suggestion
let initialTableTag = 
```

2020-12-30 12:51 UTC, myzktkyk commented on index.js
> +    var id = this.getAttribute('id');
`var` は利用しないようにしてほしいです。

```suggestion
    const id = this.getAttribute('id');
```

2020-12-30 12:51 UTC, myzktkyk commented on index.js
> +        for (var k=0; k < removeBtn.length; k++) {
`var` は利用しないようにしてほしいです。
```suggestion
        for (let k=0; k < removeBtn.length; k++) {
```

2020-12-30 12:51 UTC, myzktkyk commented on index.js
> +    if(newTask.value == ""){
`==` ではなく `===` を使うようにして下さい

```suggestion
    if(newTask.value === ""){
```

2020-12-30 12:51 UTC, myzktkyk commented on index.js
> +        newTask.value == ""
比較ではなく、代入をされたい…のですよね？

```suggestion
        newTask.value = ""
```

2020-12-30 16:18 UTC, nagamoridaiki commented on index.js
> +let inicialTableTag =
initialTableTagが正しいスペルでした。。ありがとうございます。

2020-12-30 16:19 UTC, nagamoridaiki commented on index.js
> +    var id = this.getAttribute('id');
constに変更しました。

2020-12-30 16:19 UTC, nagamoridaiki commented on index.js
> +        for (var k=0; k < removeBtn.length; k++) {
letに変更しました。

2020-12-30 16:20 UTC, nagamoridaiki commented on index.js
> +    if(newTask.value == ""){
修正しました。

2020-12-30 16:20 UTC, nagamoridaiki commented on index.js
> +        newTask.value == ""
代入がしたかったです。ご指摘ありがとうございます。

2020-12-31 23:40 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-12-31 23:40 UTC, kouki-iwahara commented on index.js
> +    'running' : '作業中',
keyは文字列にする必要はないです。
`const progressStatus = { running: '作業中', .....}`

2020-12-31 23:40 UTC, kouki-iwahara commented on index.js
> +            '<button id="'+ i + '" class=next>' + tasks[i].progress + '</button>' +
要素を文字列で作成すると、ただの文字列の扱いになりjsでの操作が難しくなります。
createElementを使用すると良いでしょう。
https://developer.mozilla.org/ja/docs/Web/API/Document/createElement

2020-12-31 23:40 UTC, kouki-iwahara commented on index.js
> +    tasks[id].progress == '作業中' ? tasks[id].progress = '完了' : tasks[id].progress = '作業中'
比較は==ではなく===を使用しましょう。

2020-12-31 23:40 UTC, kouki-iwahara commented on index.js
> +        for (let n=0; n < nextbtn.length; n++) {
=の前後にはスペースを空けましょう。
`let n = 0`

2020-12-31 23:40 UTC, kouki-iwahara commented on index.js
>          alert("入力が空です。")
今回は課題なので修正は不要でが、
alertはUXの低下を招くので使用を避けましょう。

2020-12-31 23:40 UTC, kouki-iwahara commented on index.js
>      if(newTask.value === ""){
文字列は`''`で統一しましょう。

2021-01-01 02:30 UTC, nagamoridaiki commented on index.js
> +    'running' : '作業中',
ありがとうございます。修正しました。

2021-01-01 02:32 UTC, nagamoridaiki commented on index.js
> +    tasks[id].progress == '作業中' ? tasks[id].progress = '完了' : tasks[id].progress = '作業中'
ご指摘ありがとうございます。===を使用しました。

2021-01-01 02:32 UTC, nagamoridaiki commented on index.js
> +        for (let n=0; n < nextbtn.length; n++) {
修正しました。

2021-01-01 02:33 UTC, nagamoridaiki commented on index.js
>          alert("入力が空です。")
ありがとうございます。普段、alertは極力使用を控えます。

2021-01-02 03:18 UTC, nagamoridaiki commented on index.js
> +            '<button id="'+ i + '" class=next>' + tasks[i].progress + '</button>' +
setAttributeを使用してid属性を付与しました。

2021-01-04 21:05 UTC, keni1211 commented on index.js
>  function removeItem(){
()のあとにはスペースをいれるようにしましょう。
ほかも同様です。

2021-01-04 21:13 UTC, keni1211 reviewed
動作問題ありませんので、コメント修正後は次の課題へお進みください！

2021-01-04 21:13 UTC, keni1211 commented on index.js
>  function removeItem(){
()のあとにはスペースをいれるようにしましょう。
ほかにも同様にスペースが空いていない箇所がありますので、確認をお願いいたします。

2021-01-15 09:45 UTC, merged